// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.hc.formats.protobuf;

public final class TestOuterClassname {
  private TestOuterClassname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flink_Test_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flink_Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_flink_Test_SiMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_flink_Test_SiMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022\005flink\"y\n\004Test\022\014\n\004name\030\001 \001(" +
      "\t\022\r\n\005names\030\002 \003(\t\022&\n\006si_map\030\007 \003(\0132\026.flink" +
      ".Test.SiMapEntry\032,\n\nSiMapEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\005:\0028\001B/\n\027com.hc.formats" +
      ".protobufB\022TestOuterClassnameP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_flink_Test_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_flink_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flink_Test_descriptor,
        new String[] { "Name", "Names", "SiMap", });
    internal_static_flink_Test_SiMapEntry_descriptor =
      internal_static_flink_Test_descriptor.getNestedTypes().get(0);
    internal_static_flink_Test_SiMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_flink_Test_SiMapEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
