// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.hc.formats.protobuf;

public interface TestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flink.Test)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string names = 2;</code>
   * @return A list containing the names.
   */
  java.util.List<String>
      getNamesList();
  /**
   * <code>repeated string names = 2;</code>
   * @return The count of names.
   */
  int getNamesCount();
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the element to return.
   * @return The names at the given index.
   */
  String getNames(int index);
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the names at the given index.
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);

  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */
  int getSiMapCount();
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */
  boolean containsSiMap(
          String key);
  /**
   * Use {@link #getSiMapMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Integer>
  getSiMap();
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */
  java.util.Map<String, Integer>
  getSiMapMap();
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */

  int getSiMapOrDefault(
          String key,
          int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */

  int getSiMapOrThrow(
          String key);
}
